[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "astro-ml"
version = "1.0.0"
dependencies = []   # all in requirements.txt

[project.scripts]
astro-train = "scripts.train:main"
