image:
  repository: ghcr.io/you/astro-ml
  tag: latest

replicaCount: 3

service:
  port: 8888

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: api.astro-trading.io
      paths: ["/"]

resources:
  limits:
    nvidia.com/gpu: "1"
  requests:
    cpu: 500m
    memory: 1Gi

cronjobs:
  training:
    schedule: "0 22 * * *"
    command: ["python", "scripts/train.py", "--ticker", "ALL"]
