apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: astro-ml
  annotations: {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts: {{- toYaml (pluck "host" .Values.ingress.hosts) | nindent 4 }}
    secretName: astro-ml-tls
  rules:
  - host: {{ (index .Values.ingress.hosts 0).host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: {name: astro-ml, port: {number: 8888}}
